##### Copyright 2020 The TensorFlow Authors.

In [1]:
pip install gensim

In [2]:
import gensim

In [3]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
# fse/word2vec-google-news-300

In [4]:
vec_king=wv['king']

In [5]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [6]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [7]:
wv.similarity('hockey','sports')

0.53541523

In [8]:
vec=wv['king']-wv['man']+wv['woman']

In [9]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [10]:
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [11]:
import pandas as pd

In [12]:
messages=pd.read_csv('/content/SMSSpamCollection.txt',sep='\t',names=['label','message'])

In [13]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [14]:
import re
lemmetizer=WordNetLemmatizer()
corpus=[]
for i in range(0,len(messages)):
  review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[lemmetizer.lemmatize(word) for word in review ]
  review=' '.join(review)
  corpus.append(review)

In [17]:
new_list = [(j, k) for i, j, k in zip(list(map(len,corpus)), corpus, messages['message']) if i < 1]

In [18]:
new_list

[('', '645'), ('', ':) '), ('', ':-) :-)')]

In [19]:
from nltk import sent_tokenize
nltk.download('punkt_tab')
from  gensim.utils import simple_preprocess
words=[]
for sen in corpus:
 sen_token=sent_tokenize(sen)
 for word in sen_token:
  words.append(simple_preprocess(word))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [20]:
import gensim
model=gensim.models.Word2Vec(words)

In [21]:
# getting all the vocabulary
model.wv.index_to_key


['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [22]:
model.corpus_count

5569

In [23]:
model.wv.similar_by_word('kid')

[('down', 0.9978883862495422),
 ('doe', 0.997826337814331),
 ('abt', 0.9978250861167908),
 ('again', 0.99782395362854),
 ('even', 0.9978103041648865),
 ('wanna', 0.9977648854255676),
 ('best', 0.9977610111236572),
 ('yeah', 0.9977588653564453),
 ('haha', 0.9977569580078125),
 ('meet', 0.9977566003799438)]

In [24]:
model.wv['good'].shape

(100,)

In [25]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [26]:
import numpy as np
def avg_word_vector(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [33]:
avg_word_vector(words[0]).shape

(100,)

In [27]:
!pip install tqdm

In [28]:
from tqdm import tqdm
X=[]
for i in tqdm(range(len(words))):
  X.append(avg_word_vector(words[i]))

  0%|          | 0/5569 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 4891.96it/s]


In [36]:
len(X)

5569

In [31]:
X_new=np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5569,) + inhomogeneous part.

In [ ]:
X_new[0]

In [59]:
y=messages[list(map(lambda x: len(x)>0,corpus))]
#y=pd.get_dummies(messages['label'])
y=y.iloc[:,0].values

In [60]:
y.shape

(5569,)

In [43]:
X[0].reshape(1,-1)

array([[-0.16099328,  0.23984084,  0.05586356,  0.054924  ,  0.07017244,
        -0.384309  ,  0.17564268,  0.623139  , -0.16229917, -0.18044256,
        -0.18018794, -0.40435928, -0.0706849 ,  0.08697396,  0.13883084,
        -0.18173204,  0.07679701, -0.36228624, -0.1292551 , -0.5095353 ,
         0.25309342,  0.09371126,  0.08743271, -0.1586459 , -0.03957915,
         0.03399078, -0.21404289, -0.1388441 , -0.26224032,  0.1359468 ,
         0.32183123,  0.03546752,  0.05092075, -0.23483986, -0.11979366,
         0.30743784,  0.05690239, -0.20005399, -0.20298538, -0.4772332 ,
         0.05937879, -0.16280906, -0.15383369, -0.04498444,  0.20269056,
        -0.05350943, -0.08792488, -0.08033574,  0.11936862,  0.15605554,
         0.09906033, -0.28335723, -0.0791334 ,  0.02876713, -0.12869088,
         0.17937842,  0.13753493,  0.05107959, -0.34244967,  0.05970311,
         0.08838055,  0.09416351,  0.01797758, -0.05156987, -0.24677205,
         0.2682551 ,  0.11406137,  0.2378835 , -0.3

In [54]:
df = pd.DataFrame()
for i in range(len(X)):
    row = pd.Series(X[i])
    df = pd.concat([df, row.to_frame().T], ignore_index=True)

/tmp/ipython-input-2559917599.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, row.to_frame().T], ignore_index=True)
/tmp/ipython-input-2559917599.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, row.to_frame().T], ignore_index=True)
/tmp/ipython-input-2559917599.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determi

In [55]:
df

0         1         2         3         4         5         6   \
0    -0.160993  0.239841  0.055864  0.054924  0.070172 -0.384309  0.175643   
1    -0.143905  0.199590  0.045907  0.047175  0.064188 -0.319077  0.134046   
2    -0.176168  0.254618  0.065200  0.069161  0.052838 -0.426879  0.181148   
3    -0.225883  0.319789  0.067668  0.078247  0.097448 -0.512852  0.225638   
4    -0.194308  0.262421  0.062115  0.063731  0.087521 -0.432693  0.187095   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.192965  0.296034  0.083810  0.074731  0.072679 -0.472143  0.218198   
5565 -0.211099  0.279908  0.061694  0.075673  0.090090 -0.471006  0.204744   
5566 -0.220143  0.322199  0.072603  0.063934  0.085395 -0.504403  0.229230   
5567 -0.198564  0.287261  0.068237  0.067767  0.079017 -0.464299  0.203511   
5568 -0.223222  0.304432  0.071753  0.076750  0.090836 -0.504731  0.214253   

            7         8         9   ...        90        91        92  \
0     0.623139 -0.162299 -0.180443  ...  0.313562  0.102408  0.058372   
1     0.519863 -0.132927 -0.144830  ...  0.266145  0.080282  0.044133   
2     0.627502 -0.172249 -0.211463  ...  0.317021  0.097223  0.047076   
3     0.842314 -0.219831 -0.236110  ...  0.424329  0.133262  0.076707   
4     0.711626 -0.189299 -0.206495  ...  0.359837  0.110570  0.066675   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.737325 -0.199638 -0.233875  ...  0.375174  0.118773  0.068139   
5565  0.751532 -0.211401 -0.218456  ...  0.384323  0.122854  0.052533   
5566  0.836510 -0.216419 -0.246650  ...  0.420614  0.144911  0.085626   
5567  0.750133 -0.197282 -0.227141  ...  0.374214  0.122834  0.075985   
5568  0.818391 -0.212516 -0.246134  ...  0.403794  0.130850  0.081184   

            93        94        95        96        97        98        99  
0     0.063014  0.560575  0.242207  0.186658 -0.229794  0.190626 -0.023264  
1     0.047623  0.453897  0.196302  0.156472 -0.197952  0.162218 -0.027519  
2     0.049904  0.591653  0.232999  0.152985 -0.273480  0.221825 -0.016521  
3     0.088136  0.735800  0.328611  0.263648 -0.313739  0.252927 -0.036221  
4     0.076391  0.619148  0.274151  0.213378 -0.274225  0.208117 -0.028703  
...        ...       ...       ...       ...       ...       ...       ...  
5564  0.063879  0.686921  0.276527  0.189835 -0.294154  0.245447 -0.021966  
5565  0.069306  0.664286  0.282661  0.207154 -0.305928  0.235413 -0.018329  
5566  0.093892  0.741746  0.330198  0.260554 -0.295639  0.244757 -0.033385  
5567  0.080033  0.672148  0.292412  0.218529 -0.279798  0.223684 -0.034198  
5568  0.084851  0.720401  0.320969  0.239317 -0.310185  0.235895 -0.036703  

[5569 rows x 100 columns]

In [61]:
df['output']=y

0         1         2         3         4         5         6  \
0    -0.160993  0.239841  0.055864  0.054924  0.070172 -0.384309  0.175643   
1    -0.143905  0.199590  0.045907  0.047175  0.064188 -0.319077  0.134046   
2    -0.176168  0.254618  0.065200  0.069161  0.052838 -0.426879  0.181148   
3    -0.225883  0.319789  0.067668  0.078247  0.097448 -0.512852  0.225638   
4    -0.194308  0.262421  0.062115  0.063731  0.087521 -0.432693  0.187095   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.192965  0.296034  0.083810  0.074731  0.072679 -0.472143  0.218198   
5565 -0.211099  0.279908  0.061694  0.075673  0.090090 -0.471006  0.204744   
5566 -0.220143  0.322199  0.072603  0.063934  0.085395 -0.504403  0.229230   
5567 -0.198564  0.287261  0.068237  0.067767  0.079017 -0.464299  0.203511   
5568 -0.223222  0.304432  0.071753  0.076750  0.090836 -0.504731  0.214253   

             7         8         9  ...        91        92        93  \
0     0.623139 -0.162299 -0.180443  ...  0.102408  0.058372  0.063014   
1     0.519863 -0.132927 -0.144830  ...  0.080282  0.044133  0.047623   
2     0.627502 -0.172249 -0.211463  ...  0.097223  0.047076  0.049904   
3     0.842314 -0.219831 -0.236110  ...  0.133262  0.076707  0.088136   
4     0.711626 -0.189299 -0.206495  ...  0.110570  0.066675  0.076391   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.737325 -0.199638 -0.233875  ...  0.118773  0.068139  0.063879   
5565  0.751532 -0.211401 -0.218456  ...  0.122854  0.052533  0.069306   
5566  0.836510 -0.216419 -0.246650  ...  0.144911  0.085626  0.093892   
5567  0.750133 -0.197282 -0.227141  ...  0.122834  0.075985  0.080033   
5568  0.818391 -0.212516 -0.246134  ...  0.130850  0.081184  0.084851   

            94        95        96        97        98        99  output  
0     0.560575  0.242207  0.186658 -0.229794  0.190626 -0.023264     ham  
1     0.453897  0.196302  0.156472 -0.197952  0.162218 -0.027519     ham  
2     0.591653  0.232999  0.152985 -0.273480  0.221825 -0.016521    spam  
3     0.735800  0.328611  0.263648 -0.313739  0.252927 -0.036221     ham  
4     0.619148  0.274151  0.213378 -0.274225  0.208117 -0.028703     ham  
...        ...       ...       ...       ...       ...       ...     ...  
5564  0.686921  0.276527  0.189835 -0.294154  0.245447 -0.021966    spam  
5565  0.664286  0.282661  0.207154 -0.305928  0.235413 -0.018329     ham  
5566  0.741746  0.330198  0.260554 -0.295639  0.244757 -0.033385     ham  
5567  0.672148  0.292412  0.218529 -0.279798  0.223684 -0.034198     ham  
5568  0.720401  0.320969  0.239317 -0.310185  0.235895 -0.036703     ham  

[5569 rows x 101 columns]

In [64]:
df.isnull().sum()
df.dropna(inplace=True)

In [66]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
         ..
96        0
97        0
98        0
99        0
output    0
Length: 101, dtype: int64

In [68]:
y=df['output']
df.drop('output',axis=1,inplace=True)

In [69]:
X=df

In [70]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

0         1         2         3         4         5         6   \
1828 -0.213667  0.327267  0.087038  0.085898  0.092206 -0.535260  0.229446   
3728 -0.201105  0.359255  0.095446  0.091164  0.077976 -0.558139  0.262304   
625  -0.187577  0.258957  0.061924  0.068478  0.073458 -0.427004  0.181367   
2253 -0.131187  0.180952  0.038558  0.039637  0.055878 -0.284545  0.124097   
501  -0.193849  0.271586  0.067023  0.065464  0.076182 -0.442269  0.191701   

            7         8         9   ...        90        91        92  \
1828  0.845668 -0.225301 -0.265855  ...  0.434852  0.122091  0.055286   
3728  0.867924 -0.235909 -0.266556  ...  0.445393  0.138595  0.062229   
625   0.682090 -0.183203 -0.214317  ...  0.345138  0.107679  0.061209   
2253  0.473873 -0.121409 -0.133687  ...  0.238020  0.069521  0.041947   
501   0.707876 -0.187850 -0.215441  ...  0.355849  0.115015  0.068205   

            93        94        95        96        97        98        99  
1828  0.060305  0.740580  0.292136  0.215964 -0.343637  0.250393 -0.030347  
3728  0.072065  0.799872  0.302886  0.220822 -0.341616  0.281288 -0.043465  
625   0.068630  0.605091  0.252966  0.194351 -0.268534  0.203003 -0.023769  
2253  0.049111  0.416484  0.193106  0.144734 -0.177706  0.137096 -0.014808  
501   0.069325  0.642598  0.271985  0.203569 -0.276819  0.222232 -0.025564  

[5 rows x 100 columns]

In [72]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [73]:
y_pred=classifier.predict(X_test)

In [75]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(accuracy_score(y_test,y_pred))

[[945  10]
 [ 25 132]]
0.9685251798561151
